{{- if and .Values.acl.enabled .Values.acl.sync.enabled .Values.acl.sync.source.token (not .Values.acl.sync.source.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.aclSyncSourceSecretName" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.acl.sync.source.token | quote }}
{{- end -}}
