{{- if .Values.secretsEnv -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.fullname" . }}-extra-env
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secretsEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end -}}
