apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.fullname" . }}-headless
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: headscale
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
