{{- if and .Values.ha.consul.acl.enabled .Values.ha.consul.acl.token.value (not .Values.ha.consul.acl.token.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.consulAclSecretName" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.ha.consul.acl.token.value | quote }}
  acl-tokens.json: |
    {
      "acl": {
        "tokens": {
          "initial_management": {{ .Values.ha.consul.acl.token.value | quote }},
          "agent": {{ .Values.ha.consul.acl.token.value | quote }},
          "default": {{ .Values.ha.consul.acl.token.value | quote }}
        }
      }
    }
{{- end -}}
