{{- if not .Values.database.postgres.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.postgresSecretName" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.postgres.password | quote }}
{{- end -}}
