apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.consulFullname" . }}-headless
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: consul-server
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: consul-server
  ports:
    - name: http
      port: 8500
    - name: serf-lan
      port: 8301
    - name: server
      port: 8300
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.consulFullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: consul-server
spec:
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: consul-server
  ports:
    - name: http
      port: 8500
